# -*- coding: utf-8 -*-
"""input data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOEHhO6F2TE9x4fWZeDDR2jkH-mey75r
"""

def input_produk_agro():
    print("================ UTAMA: FORM INPUT AGRO (VERSI AB) ================")

    nama_produk = input("Nama Produk (cth: Minyak Kelapa Sawit, Kopi Arabika): ")
    kategori = input("Kategori (cth: Perkebunan, Peternakan, Pangan Olahan): ")

    # Validasi input angka untuk stok dan harga
    while True:
        try:
            stok = float(input("Jumlah Stok (kg/liter): "))
            harga = float(input("Harga per Unit (Rp): "))
            break
        except ValueError:
            print("Error: Stok dan harga harus berupa angka! Silakan coba lagi.\n")

    grade = input("Grade Kualitas (A/B/C): ").upper()

    # Menyimpan data dalam bentuk Dictionary
    data_produk = {
        "nama": nama_produk,
        "kategori": kategori,
        "stok": stok,
        "harga": harga,
        "grade": grade,
        "total_nilai": stok * harga
    }

    return data_produk

# --- CONTOH PENGGUNAAN ---
daftar_inventaris = []

# Input 1 data produk
produk_baru = input_produk_agro()
daftar_inventaris.append(produk_baru)

# Menampilkan hasil input
print("\n=== DATA PRODUK BERHASIL DISIMPAN ===")
for key, value in produk_baru.items():
    if key == "harga" or key == "total_nilai":
        print(f"{key.capitalize().replace('_', ' ')}: Rp {value:,.2f}")
    else:
        print(f"{key.capitalize().replace('_', ' ')}: {value}")
