# -*- coding: utf-8 -*-
"""laporan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SyJW_KUt1tItqLsum8qIda9KTRlGlIkt
"""

def buat_laporan_agro(daftar_produk):
    if not daftar_produk:
        print("\n[!] Belum ada data produk agroindustri yang tersimpan.")
        return

    print("\n" + "="*80)
    print("                      LAPORAN INVENTARIS AGROINDUSTRI")
    print("="*80)

    # Header Tabel
    print(f"{'No':<3} | {'Nama Produk':<22} | {'Kategori':<15} | {'Stok':<10} | {'Grade':<5} | {'Total Nilai (Rp)':<18}")
    print("-" * 80)

    # Variabel Rekapitulasi
    total_nilai_inventaris = 0
    total_stok_keseluruhan = 0
    kategori_count = {}

    # Baris Data
    for idx, p in enumerate(daftar_produk, start=1):
        print(f"{idx:<3} | {p['nama']:<22} | {p['kategori']:<15} | {p['stok']:<10.1f} | {p['grade']:<5} | Rp {p['total_nilai']:>15,.2f}")

        # Akumulasi statistik
        total_nilai_inventaris += p['total_nilai']
        total_stok_keseluruhan += p['stok']

        # Hitung jumlah per kategori
        kat = p['kategori']
        kategori_count[kat] = kategori_count.get(kat, 0) + 1

    print("-" * 80)

    # Ringkasan Laporan
    print("\n--- RINGKASAN REKAPITULASI ---")
    print(f"Total Jenis Produk      : {len(daftar_produk)} item")
    print(f"Total Volume Stok       : {total_stok_keseluruhan:,.1f} kg/liter")
    print(f"Total Nilai Inventaris  : Rp {total_nilai_inventaris:,.2f}")

    print("\nSebaran Produk per Kategori:")
    for kat, jumlah in kategori_count.items():
        print(f" - {kat}: {jumlah} produk")
    print("="*80)


# --- CONTOH PEMANGGILAN FUNGSI ---
# Data tiruan yang sesuai dengan format fungsi input sebelumnya
data_inventaris = [
    {"nama": "Minyak Sawit CPO", "kategori": "Perkebunan", "stok": 500.0, "harga": 14000.0, "grade": "A", "total_nilai": 7000000.0},
    {"nama": "Kopi Arabika", "kategori": "Perkebunan", "stok": 120.0, "harga": 95000.0, "grade": "A", "total_nilai": 11400000.0},
    {"nama": "Keripik Nanas", "kategori": "Olahan", "stok": 50.0, "harga": 25000.0, "grade": "B", "total_nilai": 1250000.0}
]

# Jalankan fungsi
buat_laporan_agro(data_inventaris)